version: '3.3'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass


  app:
    build: .
    ports:
      - "127.0.0.1:12800:8080"
    restart: unless-stopped
    environment:
      DATABASE_URL: "mongodb://db:27017"


